pub(crate) fn assert_lifecycle_contract(schema: &serde_json::Value) {
    assert!(schema["components"]["schemas"]["ModelVersion"]["required"]
        .as_array()
        .unwrap()
        .iter()
        .any(|field| field == "review_mode"));
    assert_eq!(
        schema["components"]["schemas"]["ModelVersion"]["properties"]["review_mode"]["enum"][2],
        "both"
    );
    assert_eq!(
        schema["paths"]["/api/v1/ops/routing-policies"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/RoutingPolicyListResponse"
    );
    assert_eq!(
        schema["components"]["schemas"]["RoutingPolicyListResponse"]["properties"]["policies"]
            ["items"]["$ref"],
        "#/components/schemas/RoutingPolicyRecord"
    );
    assert_eq!(
        schema["components"]["schemas"]["RoutingPolicyRecord"]["properties"]["review_mode"]["enum"]
            [2],
        "both"
    );
    assert_eq!(
        schema["components"]["schemas"]["RoutingPolicyRecord"]["properties"]["risk_thresholds"]
            ["$ref"],
        "#/components/schemas/RiskThresholds"
    );
    assert_eq!(
        schema["paths"]["/api/v1/ops/routing-policies"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/SaveRoutingPolicyCandidateRequest"
    );
    assert_eq!(
        schema["paths"]["/api/v1/ops/routing-policies"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/RoutingPolicyRecord"
    );
    assert_eq!(
        schema["components"]["schemas"]["SaveRoutingPolicyCandidateRequest"]["properties"]
            ["policy"]["$ref"],
        "#/components/schemas/RoutingPolicy"
    );
    assert_eq!(
        schema["components"]["schemas"]["RoutingPolicy"]["properties"]["policy_id"]["minLength"],
        1
    );
    assert_eq!(
        schema["components"]["schemas"]["SaveRoutingPolicyCandidateRequest"]["properties"]["owner"]
            ["minLength"],
        1
    );
    assert_eq!(
        schema["paths"]
            ["/api/v1/ops/routing-policies/{policy_id}/{review_mode}/{version}/activate"]["post"]
            ["responses"]["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/RoutingPolicyRecord"
    );
    for action in ["submit", "approve", "activate", "rollback"] {
        let operation = &schema["paths"][format!(
            "/api/v1/ops/routing-policies/{{policy_id}}/{{review_mode}}/{{version}}/{action}"
        )]["post"];
        assert_eq!(
            operation["requestBody"]["content"]["application/json"]["schema"]["$ref"],
            "#/components/schemas/RoutingPolicyLifecycleRequest"
        );
    }
    assert_eq!(
        schema["components"]["schemas"]["RoutingPolicyLifecycleRequest"]["properties"]
            ["evidence_refs"]["minItems"],
        1
    );
    assert_eq!(
        schema["components"]["schemas"]["RoutingPolicyLifecycleRequest"]["properties"]
            ["evidence_refs"]["items"]["minLength"],
        1
    );
    assert!(
        schema["components"]["schemas"]["RoutingPolicyLifecycleRequest"]["properties"]
            ["evidence_refs"]["description"]
            .as_str()
            .unwrap_or_default()
            .contains("must not contain PII")
    );
    assert_eq!(
        schema["paths"]
            ["/api/v1/ops/routing-policies/{policy_id}/{review_mode}/{version}/promotion-gates"]
            ["get"]["responses"]["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/RoutingPolicyPromotionGatesResponse"
    );
    assert_eq!(
        schema["components"]["schemas"]["RoutingPolicyPromotionGatesResponse"]["properties"]
            ["gates"]["items"]["$ref"],
        "#/components/schemas/RoutingPolicyPromotionGate"
    );
    assert_eq!(
        schema["paths"]
            ["/api/v1/ops/routing-policies/{policy_id}/{review_mode}/{version}/rollback"]["post"]
            ["parameters"][1]["name"],
        "review_mode"
    );
    assert_eq!(
        schema["paths"]["/api/v1/ops/models/{model_key}/activate"]["post"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ModelLifecycleResponse"
    );
    assert_eq!(
        schema["paths"]["/api/v1/ops/models/{model_key}/rollback"]["post"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ModelLifecycleResponse"
    );
    assert!(
        schema["paths"]["/api/v1/ops/models/{model_key}/rollback"]["post"]["summary"]
            .as_str()
            .unwrap_or_default()
            .contains("previous active"),
        "model rollback summary must describe previous active rollback semantics"
    );
    for action in ["activate", "rollback"] {
        let operation =
            &schema["paths"][format!("/api/v1/ops/models/{{model_key}}/{action}")]["post"];
        assert_eq!(
            operation["requestBody"]["content"]["application/json"]["schema"]["$ref"],
            "#/components/schemas/ModelLifecycleRequest"
        );
    }
    assert_eq!(
        schema["components"]["schemas"]["ModelLifecycleRequest"]["properties"]["evidence_refs"]
            ["minItems"],
        1
    );
    assert_eq!(
        schema["components"]["schemas"]["ModelLifecycleRequest"]["properties"]["evidence_refs"]
            ["items"]["minLength"],
        1
    );
    assert!(
        schema["components"]["schemas"]["ModelLifecycleRequest"]["properties"]["evidence_refs"]
            ["description"]
            .as_str()
            .unwrap_or_default()
            .contains("must not contain PII")
    );
    assert_eq!(
        schema["components"]["schemas"]["ModelLifecycleRequest"]["properties"]["evidence_refs"]
            ["contains"]["pattern"],
        "^model_versions:[^:]+:[^:]+$"
    );
    assert!(
        schema["components"]["schemas"]["ModelLifecycleRequest"]["properties"]["evidence_refs"]
            ["description"]
            .as_str()
            .unwrap_or_default()
            .contains("activation target or rollback active version")
    );
    assert!(
        schema["components"]["schemas"]["ModelLifecycleResponse"]["required"]
            .as_array()
            .unwrap()
            .iter()
            .any(|field| field == "status")
    );
    assert!(
        schema["components"]["schemas"]["RulePromotionGatesResponse"]["required"]
            .as_array()
            .unwrap()
            .iter()
            .any(|field| field == "review_mode")
    );
    assert_eq!(
        schema["components"]["schemas"]["RulePromotionGatesResponse"]["properties"]["review_mode"]
            ["enum"][1],
        "post_payment"
    );
    assert!(
        schema["components"]["schemas"]["ModelPromotionGatesResponse"]["required"]
            .as_array()
            .unwrap()
            .iter()
            .any(|field| field == "review_mode")
    );
    assert_eq!(
        schema["components"]["schemas"]["ModelPromotionGatesResponse"]["properties"]["review_mode"]
            ["enum"][0],
        "pre_payment"
    );
    assert!(
        schema["components"]["schemas"]["RulePromotionGate"]["required"]
            .as_array()
            .unwrap()
            .iter()
            .any(|field| field == "evidence_source")
    );
    assert_eq!(
        schema["components"]["schemas"]["RulePromotionGate"]["properties"]["evidence_source"]
            ["enum"][1],
        "backtest"
    );
    assert!(
        schema["components"]["schemas"]["ModelPromotionGate"]["required"]
            .as_array()
            .unwrap()
            .iter()
            .any(|field| field == "evidence_source")
    );
    assert!(
        schema["components"]["schemas"]["ModelPromotionGate"]["properties"]["evidence_source"]
            ["enum"]
            .as_array()
            .unwrap()
            .iter()
            .any(|field| field == "evaluation")
    );
    assert!(
        schema["components"]["schemas"]["RuleBacktestResponse"]["required"]
            .as_array()
            .unwrap()
            .iter()
            .any(|field| field == "precision")
    );
    assert!(
        schema["components"]["schemas"]["RuleBacktestResponse"]["required"]
            .as_array()
            .unwrap()
            .iter()
            .any(|field| field == "promotion_recommendation")
    );
}
