#!/usr/bin/env python3
"""Execute the portable MLOps monitoring plan as a local staging simulator."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse


EXPECTED_JOBS = {
    "shadow_traffic_evaluation": "shadow_report.json",
    "drift_monitoring": "drift_report.json",
    "segment_fairness_review": "fairness_report.json",
    "reviewer_disagreement_review": "reviewer_disagreement_report.json",
    "label_delay_review": "label_delay_report.json",
}


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def local_name_from_uri(uri: str, fallback: str) -> str:
    if not uri:
        return fallback
    parsed = urlparse(uri)
    name = Path(parsed.path).name
    return name or fallback


def report_for_job(plan: dict, job: dict, generated_at: str) -> dict:
    job_kind = job.get("job_kind")
    return {
        "artifact_kind": job_kind,
        "generated_at": generated_at,
        "model_key": plan.get("model_key"),
        "model_version": plan.get("model_version"),
        "manifest_uri": plan.get("manifest_uri"),
        "artifact_uri": plan.get("artifact_uri"),
        "status": "staging_simulated",
        "customer_data_required": False,
        "checks": [
            {"name": "plan_job_present", "status": "passed"},
            {"name": "output_ref_declared", "status": "passed" if job.get("output_ref") else "missing"},
            {"name": "no_routing_impact", "status": "passed"},
        ],
        "boundary": "generated by staging simulator; not live customer shadow or drift evidence",
    }


def run_plan(plan_path: Path, output_dir: Path) -> dict:
    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    if plan.get("plan_kind") != "scheduled_mlops_monitoring":
        raise ValueError("plan_kind must be scheduled_mlops_monitoring")

    jobs = plan.get("jobs")
    if not isinstance(jobs, list):
        raise ValueError("plan jobs must be a list")

    generated_at = datetime.now(timezone.utc).isoformat()
    seen = set()
    artifacts = []
    for job in jobs:
        job_kind = job.get("job_kind")
        if job_kind not in EXPECTED_JOBS:
            raise ValueError(f"unexpected monitoring job_kind: {job_kind}")
        seen.add(job_kind)
        uri_key = next((key for key in job if key.endswith("_uri")), "")
        file_name = local_name_from_uri(str(job.get(uri_key, "")), EXPECTED_JOBS[job_kind])
        write_json(output_dir / file_name, report_for_job(plan, job, generated_at))
        artifacts.append(file_name)

    missing = sorted(set(EXPECTED_JOBS) - seen)
    if missing:
        raise ValueError(f"monitoring plan missing jobs: {', '.join(missing)}")

    index = {
        "artifact_kind": "staging_mlops_monitoring_execution",
        "generated_at": generated_at,
        "plan_path": str(plan_path),
        "artifacts": artifacts,
        "status": "completed",
        "customer_data_required": False,
    }
    write_json(output_dir / "index.json", index)
    return index


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--plan", required=True, help="Path to scheduled_mlops_monitoring JSON plan")
    parser.add_argument("--output-dir", default="artifacts/mlops-monitoring")
    args = parser.parse_args()

    index = run_plan(Path(args.plan), Path(args.output_dir))
    print(json.dumps(index, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
