apiVersion: v1
kind: Namespace
metadata:
  name: nwfwa-observability
  labels:
    app.kubernetes.io/name: nwfwa-observability
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
