apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nwfwa-staging
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - object-storage.yaml
  - clickhouse.yaml
  - database-jobs.yaml
  - ml-service.yaml
  - api-server.yaml
  - worker-cronjobs.yaml
  - web-console.yaml
