FROM postgres:16

WORKDIR /app
COPY migrations ./migrations
COPY scripts/demo/seed_demo.sql ./scripts/demo/seed_demo.sql
COPY scripts/demo/assert_demo_persistence.sql ./scripts/demo/assert_demo_persistence.sql
CMD ["psql", "--version"]
