use crate::{
    app::AppState,
    routes::{
        agent, claims, dashboard, health, inbox, knowledge, openapi, ops_agents, ops_audit,
        ops_bootstrap, ops_cases, ops_datasets, ops_evidence, ops_medical, ops_models,
        ops_providers, ops_routing_policies, ops_rules, ops_sampling, ops_schemes, pilot_loop,
    },
};
use axum::{
    routing::{get, post},
    Router,
};

pub(super) fn register_api_routes(router: Router<AppState>) -> Router<AppState> {
    router
        .route("/api/openapi.json", get(openapi::openapi_schema))
        .route("/api/v1/health", get(health::health))
        .route("/api/v1/claims/score", post(claims::score_claim))
        .route(
            "/api/v1/inbox/claims/normalize",
            post(inbox::normalize_claim_inbox),
        )
        .route(
            "/api/v1/ops/dashboard/summary",
            get(dashboard::dashboard_summary),
        )
        .route(
            "/api/v1/ops/webhook-events",
            get(pilot_loop::list_webhook_events),
        )
        .route(
            "/api/v1/ops/webhook-events/:event_id/delivery-attempts",
            post(pilot_loop::submit_webhook_delivery_attempt),
        )
        .route("/api/v1/ops/alerts", get(pilot_loop::list_ops_alerts))
        .route("/api/v1/ops/leads", get(ops_cases::list_leads))
        .route(
            "/api/v1/ops/leads/:lead_id/triage",
            post(ops_cases::triage_lead),
        )
        .route("/api/v1/ops/cases", get(ops_cases::list_cases))
        .route(
            "/api/v1/ops/cases/:case_id/status",
            post(ops_cases::update_case_status),
        )
        .route(
            "/api/v1/ops/backfills",
            get(ops_bootstrap::list_historical_backfills)
                .post(ops_bootstrap::create_historical_backfill),
        )
        .route(
            "/api/v1/ops/backfills/:job_id/leads",
            get(ops_bootstrap::list_historical_backfill_leads),
        )
        .route(
            "/api/v1/ops/evidence-requests",
            get(ops_bootstrap::list_evidence_requests),
        )
        .route(
            "/api/v1/ops/evidence-requests/generate",
            post(ops_bootstrap::generate_evidence_requests),
        )
        .route(
            "/api/v1/ops/evidence-requests/:request_id/status",
            post(ops_bootstrap::update_evidence_request_status),
        )
        .route(
            "/api/v1/ops/label-bootstrap/queue",
            get(ops_bootstrap::label_bootstrap_queue),
        )
        .route(
            "/api/v1/ops/label-bootstrap/items/:item_id/review",
            post(ops_bootstrap::review_label_bootstrap_item),
        )
        .route(
            "/api/v1/ops/audit-samples",
            get(ops_sampling::list_audit_samples).post(ops_sampling::create_audit_sample),
        )
        .route(
            "/api/v1/ops/audit-events",
            get(ops_audit::list_audit_events),
        )
        .route("/api/v1/ops/api-calls", get(ops_audit::list_api_calls))
        .route("/api/v1/ops/agent-runs", get(ops_agents::list_agent_runs))
        .route(
            "/api/v1/ops/agent-runs/:agent_run_id/approvals",
            post(ops_agents::submit_agent_approval),
        )
        .route(
            "/api/v1/ops/agent-runs/:agent_run_id/cancel",
            post(ops_agents::cancel_agent_run),
        )
        .route(
            "/api/v1/agent/cases/investigate",
            post(agent::investigate_case),
        )
        .route(
            "/api/v1/ops/knowledge/cases",
            get(knowledge::list_cases).post(knowledge::publish_case),
        )
        .route(
            "/api/v1/knowledge/search-similar",
            post(knowledge::search_similar),
        )
        .route(
            "/api/v1/members/:member_id/profile-summary",
            get(pilot_loop::member_profile_summary),
        )
        .route(
            "/api/v1/investigations/results",
            post(pilot_loop::write_investigation_result),
        )
        .route("/api/v1/qa/results", post(pilot_loop::write_qa_result))
        .route(
            "/api/v1/ops/qa/feedback-items",
            get(pilot_loop::list_qa_feedback_items),
        )
        .route(
            "/api/v1/ops/qa/feedback-items/:feedback_id/status",
            post(pilot_loop::update_qa_feedback_status),
        )
        .route("/api/v1/ops/qa/queue", get(pilot_loop::list_qa_queue))
        .route(
            "/api/v1/ops/qa/queue-summary",
            get(pilot_loop::qa_queue_summary),
        )
        .route("/api/v1/ops/labels", get(pilot_loop::list_outcome_labels))
        .route(
            "/api/v1/audit/claims/:claim_id",
            get(pilot_loop::claim_audit_history),
        )
        .route("/api/v1/ops/rules", get(ops_rules::list_rules))
        .route(
            "/api/v1/ops/rules/conditions",
            get(ops_rules::list_rule_conditions),
        )
        .route("/api/v1/ops/rules/backtest", post(ops_rules::backtest_rule))
        .route(
            "/api/v1/ops/rules/performance",
            get(ops_rules::rule_performance),
        )
        .route(
            "/api/v1/ops/rules/:rule_id/promotion-gates",
            get(ops_rules::rule_promotion_gates),
        )
        .route(
            "/api/v1/ops/rules/:rule_id/promotion-reviews",
            post(ops_rules::submit_rule_promotion_review),
        )
        .route(
            "/api/v1/ops/rules/:rule_id/shadow-runs",
            post(ops_rules::submit_rule_shadow_run),
        )
        .route(
            "/api/v1/ops/rules/candidates",
            post(ops_rules::save_rule_candidate),
        )
        .route(
            "/api/v1/ops/rules/candidate-reviews",
            post(ops_rules::review_rule_candidate),
        )
        .route(
            "/api/v1/ops/rules/discover",
            post(ops_rules::discover_rules),
        )
        .route("/api/v1/ops/rules/:rule_id", get(ops_rules::get_rule))
        .route(
            "/api/v1/ops/datasets",
            get(ops_datasets::list_datasets).post(ops_datasets::register_dataset),
        )
        .route(
            "/api/v1/ops/datasets/:dataset_id",
            get(ops_datasets::get_dataset),
        )
        .route(
            "/api/v1/ops/datasets/:dataset_id/mappings",
            post(ops_datasets::add_field_mapping),
        )
        .route(
            "/api/v1/ops/factors/readiness",
            get(ops_datasets::factor_readiness),
        )
        .route(
            "/api/v1/ops/feature-sets",
            post(ops_datasets::register_feature_set),
        )
        .route(
            "/api/v1/ops/model-datasets",
            post(ops_datasets::register_model_dataset),
        )
        .route(
            "/api/v1/ops/model-evaluations",
            get(ops_datasets::list_model_evaluations).post(ops_datasets::register_model_evaluation),
        )
        .route(
            "/api/v1/ops/model-evaluations/:evaluation_run_id",
            get(ops_datasets::get_model_evaluation),
        )
        .route(
            "/api/v1/ops/scoring-feature-context-materializations",
            post(ops_datasets::submit_scoring_feature_context_materialization),
        )
        .route(
            "/api/v1/ops/clinical-compatibility-references",
            post(ops_datasets::submit_clinical_compatibility_reference),
        )
        .route(
            "/api/v1/ops/unbundling-comparator-candidates",
            post(ops_datasets::submit_unbundling_comparator_candidates),
        )
        .route(
            "/api/v1/ops/worker-data-pipeline-executions",
            post(ops_datasets::submit_worker_data_pipeline_execution_report),
        )
        .route(
            "/api/v1/ops/scoring-feature-context-materializations/:materialization_id",
            get(ops_datasets::get_scoring_feature_context_materialization),
        )
        .route(
            "/api/v1/ops/evidence/documents",
            get(ops_evidence::list_documents).post(ops_evidence::create_document),
        )
        .route(
            "/api/v1/ops/evidence/documents/:document_id",
            get(ops_evidence::get_document),
        )
        .route(
            "/api/v1/ops/evidence/documents/:document_id/chunks",
            get(ops_evidence::list_document_chunks).post(ops_evidence::create_document_chunk),
        )
        .route(
            "/api/v1/ops/evidence/documents/:document_id/ocr-outputs",
            get(ops_evidence::list_ocr_outputs).post(ops_evidence::create_ocr_output),
        )
        .route(
            "/api/v1/ops/evidence/embedding-jobs",
            get(ops_evidence::list_embedding_jobs).post(ops_evidence::create_embedding_job),
        )
        .route(
            "/api/v1/ops/evidence/retrieval-audit-events",
            get(ops_evidence::list_retrieval_audit_events)
                .post(ops_evidence::create_retrieval_audit_event),
        )
        .route("/api/v1/ops/models", get(ops_models::list_models))
        .route(
            "/api/v1/ops/routing-policies",
            get(ops_routing_policies::list_routing_policies)
                .post(ops_routing_policies::save_routing_policy_candidate),
        )
        .route(
            "/api/v1/ops/routing-policies/:policy_id/:review_mode/:version/submit",
            post(ops_routing_policies::submit_routing_policy),
        )
        .route(
            "/api/v1/ops/routing-policies/:policy_id/:review_mode/:version/promotion-gates",
            get(ops_routing_policies::routing_policy_promotion_gates),
        )
        .route(
            "/api/v1/ops/routing-policies/:policy_id/:review_mode/:version/approve",
            post(ops_routing_policies::approve_routing_policy),
        )
        .route(
            "/api/v1/ops/routing-policies/:policy_id/:review_mode/:version/activate",
            post(ops_routing_policies::activate_routing_policy),
        )
        .route(
            "/api/v1/ops/routing-policies/:policy_id/:review_mode/:version/rollback",
            post(ops_routing_policies::rollback_routing_policy),
        )
        .route(
            "/api/v1/ops/providers/risk-summary",
            get(ops_providers::provider_risk_summary),
        )
        .route(
            "/api/v1/ops/providers/anomaly-clustering-reports",
            post(ops_providers::submit_anomaly_clustering_report),
        )
        .route(
            "/api/v1/ops/providers/sanctions-sync-reports",
            post(ops_providers::submit_sanctions_sync_report),
        )
        .route(
            "/api/v1/ops/providers/profile-window-rollups",
            post(ops_providers::submit_provider_profile_window_rollup),
        )
        .route(
            "/api/v1/ops/providers/graph-signal-rollups",
            post(ops_providers::submit_provider_graph_signal_rollup),
        )
        .route(
            "/api/v1/ops/providers/peer-benchmarks",
            post(ops_providers::submit_peer_benchmark),
        )
        .route(
            "/api/v1/ops/providers/episode-rollups",
            post(ops_providers::submit_episode_rollup),
        )
        .route(
            "/api/v1/ops/providers/anomaly-review-queue",
            get(ops_providers::anomaly_review_queue),
        )
        .route(
            "/api/v1/ops/providers/anomaly-candidate-reviews",
            post(ops_providers::review_anomaly_candidate),
        )
        .route(
            "/api/v1/ops/medical-review/queue",
            get(ops_medical::medical_review_queue),
        )
        .route(
            "/api/v1/ops/medical-review/results",
            post(ops_medical::submit_medical_review_result),
        )
        .route(
            "/api/v1/ops/fwa-schemes",
            get(ops_schemes::list_fwa_schemes),
        )
        .route(
            "/api/v1/ops/models/:model_key/performance",
            get(ops_models::model_performance),
        )
        .route(
            "/api/v1/ops/models/:model_key/promotion-gates",
            get(ops_models::model_promotion_gates),
        )
        .route(
            "/api/v1/ops/models/:model_key/versions/:model_version/promotion-gates",
            get(ops_models::model_version_promotion_gates),
        )
        .route(
            "/api/v1/ops/models/:model_key/retraining-readiness",
            get(ops_models::model_retraining_readiness),
        )
        .route(
            "/api/v1/ops/models/:model_key/retraining-jobs",
            get(ops_models::list_model_retraining_jobs)
                .post(ops_models::create_model_retraining_job),
        )
        .route(
            "/api/v1/ops/models/:model_key/mlops-monitoring-review-queue",
            get(ops_models::model_monitoring_review_queue),
        )
        .route(
            "/api/v1/ops/models/:model_key/mlops-monitoring-review-tasks/:task_id/reviews",
            post(ops_models::submit_model_monitoring_review_task_review),
        )
        .route(
            "/api/v1/ops/models/:model_key/mlops-monitoring-reports",
            post(ops_models::submit_mlops_monitoring_report),
        )
        .route(
            "/api/v1/ops/models/:model_key/probability-calibration-reports",
            post(ops_models::submit_probability_calibration_report),
        )
        .route(
            "/api/v1/ops/models/:model_key/mlops-alert-deliveries",
            post(ops_models::submit_mlops_alert_delivery),
        )
        .route(
            "/api/v1/ops/models/:model_key/mlops-alert-delivery-queue",
            get(ops_models::mlops_alert_delivery_queue),
        )
        .route(
            "/api/v1/ops/models/:model_key/mlops-alert-delivery-tasks/:task_id/reviews",
            post(ops_models::submit_mlops_alert_delivery_task_review),
        )
        .route(
            "/api/v1/ops/model-retraining-jobs/:job_id/status",
            post(ops_models::update_model_retraining_job_status),
        )
        .route(
            "/api/v1/ops/model-retraining-jobs/claim-next",
            post(ops_models::claim_next_model_retraining_job),
        )
        .route(
            "/api/v1/ops/model-retraining-jobs/:job_id/output",
            post(ops_models::complete_model_retraining_job),
        )
        .route(
            "/api/v1/ops/models/:model_key/promotion-reviews",
            post(ops_models::submit_model_promotion_review),
        )
        .route(
            "/api/v1/ops/models/:model_key/versions/:model_version/promotion-reviews",
            post(ops_models::submit_model_version_promotion_review),
        )
        .route(
            "/api/v1/ops/models/:model_key/activate",
            post(ops_models::activate_model),
        )
        .route(
            "/api/v1/ops/models/:model_key/versions/:model_version/activate",
            post(ops_models::activate_model_version),
        )
        .route(
            "/api/v1/ops/models/:model_key/rollback",
            post(ops_models::rollback_model),
        )
        .route(
            "/api/v1/ops/rules/:rule_id/submit",
            post(ops_rules::submit_rule),
        )
        .route(
            "/api/v1/ops/rules/:rule_id/approve",
            post(ops_rules::approve_rule),
        )
        .route(
            "/api/v1/ops/rules/:rule_id/publish",
            post(ops_rules::publish_rule),
        )
        .route(
            "/api/v1/ops/rules/:rule_id/rollback",
            post(ops_rules::rollback_rule),
        )
}
