use super::{rule_helpers::rule_detail_from_rule, RuleDetailRecord};
use fwa_core::{RecommendedAction, RuleActionClass};
use fwa_rules::{AdjudicationPolicy, Condition, RequiredEvidence, Rule, RuleAction};

pub fn default_runtime_rules() -> Vec<Rule> {
    vec![
        Rule {
            rule_id: "rule_service_before_coverage".into(),
            version: 1,
            name: "Service before coverage start".into(),
            review_mode: "pre_payment".into(),
            scheme_family: Some("early_high_value_claim".into()),
            conditions: vec![Condition {
                field: "days_since_policy_start".into(),
                operator: "<=".into(),
                value: serde_json::json!(-1),
            }],
            action: RuleAction {
                score: 100,
                alert_code: "SERVICE_BEFORE_COVERAGE_START".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::HardDeny,
                required_evidence: vec![RequiredEvidence {
                    evidence_type: "coverage_eligibility".into(),
                    evidence_request_type: None,
                    blocking: true,
                    policy_authority_ref: Some("policy:coverage-eligibility:v1".into()),
                    exception_check: Some("no_retroactive_coverage_exception".into()),
                }],
                adjudication_policy: Some(AdjudicationPolicy {
                    customer_approval_ref: "customer-rule-list:demo:v1".into(),
                    appeal_or_override_route: "appeals:manual-review:v1".into(),
                    effective_date: "2026-01-01".into(),
                    rollback_plan_ref: "rollback:rules:v1".into(),
                    production_threshold_ref: "thresholds:prepay-hard-deny:v1".into(),
                    routing_impact_ref: "routing-impact:shadow-demo:v1".into(),
                }),
                reason: "服务日期早于保单生效日，且无追溯保障例外".into(),
            },
        },
        Rule {
            rule_id: "rule_early_claim".into(),
            version: 1,
            name: "Early claim".into(),
            review_mode: "both".into(),
            scheme_family: Some("early_high_value_claim".into()),
            conditions: vec![Condition {
                field: "days_since_policy_start".into(),
                operator: "<=".into(),
                value: serde_json::json!(7),
            }],
            action: RuleAction {
                score: 75,
                alert_code: "EARLY_CLAIM".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "保单生效后 7 天内发生理赔".into(),
            },
        },
        Rule {
            rule_id: "rule_early_high_amount".into(),
            version: 1,
            name: "Early high amount".into(),
            review_mode: "both".into(),
            scheme_family: Some("early_high_value_claim".into()),
            conditions: vec![
                Condition {
                    field: "days_since_policy_start".into(),
                    operator: "<=".into(),
                    value: serde_json::json!(10),
                },
                Condition {
                    field: "claim_amount_to_limit_ratio".into(),
                    operator: ">=".into(),
                    value: serde_json::json!(0.7),
                },
            ],
            action: RuleAction {
                score: 45,
                alert_code: "EARLY_HIGH_AMOUNT".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "保单生效早期发生高额理赔".into(),
            },
        },
        Rule {
            rule_id: "rule_high_cost_single_item".into(),
            version: 1,
            name: "High cost single item".into(),
            review_mode: "both".into(),
            scheme_family: Some("high_risk_claim".into()),
            conditions: vec![Condition {
                field: "high_cost_item_ratio".into(),
                operator: ">=".into(),
                value: serde_json::json!(0.5),
            }],
            action: RuleAction {
                score: 25,
                alert_code: "HIGH_COST_SINGLE_ITEM".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "单个高价项目占理赔金额比例偏高".into(),
            },
        },
        Rule {
            rule_id: "rule_large_limit_usage".into(),
            version: 1,
            name: "Large limit usage".into(),
            review_mode: "both".into(),
            scheme_family: Some("early_high_value_claim".into()),
            conditions: vec![Condition {
                field: "claim_amount_to_limit_ratio".into(),
                operator: ">=".into(),
                value: serde_json::json!(0.8),
            }],
            action: RuleAction {
                score: 35,
                alert_code: "LARGE_LIMIT_USAGE".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "理赔金额接近保障额度".into(),
            },
        },
        Rule {
            rule_id: "rule_low_medical_match".into(),
            version: 1,
            name: "Low medical match".into(),
            review_mode: "both".into(),
            scheme_family: Some("diagnosis_procedure_mismatch".into()),
            conditions: vec![Condition {
                field: "diagnosis_procedure_match_score".into(),
                operator: "<=".into(),
                value: serde_json::json!(0.4),
            }],
            action: RuleAction {
                score: 30,
                alert_code: "LOW_MEDICAL_MATCH".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "诊断与项目匹配度偏低".into(),
            },
        },
        Rule {
            rule_id: "rule_duplicate_claim".into(),
            version: 1,
            name: "Duplicate claim".into(),
            review_mode: "both".into(),
            scheme_family: Some("duplicate_billing".into()),
            conditions: vec![Condition {
                field: "duplicate_claim_similarity_score".into(),
                operator: ">=".into(),
                value: serde_json::json!(0.95),
            }],
            action: RuleAction {
                score: 35,
                alert_code: "DUPLICATE_CLAIM".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "同一投保人、Provider、服务日期、项目和金额疑似重复理赔".into(),
            },
        },
        Rule {
            rule_id: "rule_upcoding_complexity".into(),
            version: 1,
            name: "Upcoding complexity".into(),
            review_mode: "both".into(),
            scheme_family: Some("upcoding".into()),
            conditions: vec![
                Condition {
                    field: "diagnosis_procedure_match_score".into(),
                    operator: "<=".into(),
                    value: serde_json::json!(0.45),
                },
                Condition {
                    field: "high_cost_item_ratio".into(),
                    operator: ">=".into(),
                    value: serde_json::json!(0.5),
                },
            ],
            action: RuleAction {
                score: 35,
                alert_code: "UPCODING_COMPLEXITY".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "高复杂度或高价项目与诊断支持度偏低，疑似 upcoding".into(),
            },
        },
        Rule {
            rule_id: "rule_unbundling_component_pattern".into(),
            version: 1,
            name: "Unbundling component pattern".into(),
            review_mode: "both".into(),
            scheme_family: Some("unbundling".into()),
            conditions: vec![Condition {
                field: "claim_item_count".into(),
                operator: ">=".into(),
                value: serde_json::json!(6),
            }],
            action: RuleAction {
                score: 25,
                alert_code: "UNBUNDLING_COMPONENT_PATTERN".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "同一案件明细项目数量异常偏多，需核查是否存在拆分计费".into(),
            },
        },
        Rule {
            rule_id: "rule_medically_unnecessary_service".into(),
            version: 1,
            name: "Medically unnecessary service".into(),
            review_mode: "both".into(),
            scheme_family: Some("medically_unnecessary_service".into()),
            conditions: vec![Condition {
                field: "clinical_review_required".into(),
                operator: "==".into(),
                value: serde_json::json!(1),
            }],
            action: RuleAction {
                score: 30,
                alert_code: "MEDICALLY_UNNECESSARY_SERVICE".into(),
                recommended_action: RecommendedAction::RequestEvidence,
                action_class: RuleActionClass::PendingEvidence,
                required_evidence: vec![RequiredEvidence {
                    evidence_type: "clinical_missing_evidence".into(),
                    evidence_request_type: Some("clinical_document_request".into()),
                    blocking: true,
                    policy_authority_ref: Some("policy:clinical-evidence:v1".into()),
                    exception_check: Some("required_clinical_documents_not_present".into()),
                }],
                adjudication_policy: None,
                reason: "临床证据不足或存在缺失，需复核医疗必要性".into(),
            },
        },
        Rule {
            rule_id: "rule_same_member_repeated_service".into(),
            version: 1,
            name: "Same member repeated service".into(),
            review_mode: "both".into(),
            scheme_family: Some("excessive_utilization".into()),
            conditions: vec![Condition {
                field: "same_member_service_count_30d".into(),
                operator: ">=".into(),
                value: serde_json::json!(3),
            }],
            action: RuleAction {
                score: 25,
                alert_code: "SAME_MEMBER_REPEATED_SERVICE".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "同一投保人短期内同类服务重复出现，需核查过度使用".into(),
            },
        },
        Rule {
            rule_id: "rule_relationship_concentration".into(),
            version: 1,
            name: "Relationship concentration".into(),
            review_mode: "both".into(),
            scheme_family: Some("relationship_concentration".into()),
            conditions: vec![Condition {
                field: "provider_high_risk_neighbor_signal".into(),
                operator: "==".into(),
                value: serde_json::json!(true),
            }],
            action: RuleAction {
                score: 35,
                alert_code: "RELATIONSHIP_CONCENTRATION".into(),
                recommended_action: RecommendedAction::EscalateInvestigation,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "Provider 关系网络存在高风险邻居或集中关联信号".into(),
            },
        },
        Rule {
            rule_id: "rule_many_claim_items".into(),
            version: 1,
            name: "Many claim items".into(),
            review_mode: "both".into(),
            scheme_family: Some("excessive_utilization".into()),
            conditions: vec![Condition {
                field: "claim_item_count".into(),
                operator: ">=".into(),
                value: serde_json::json!(5),
            }],
            action: RuleAction {
                score: 20,
                alert_code: "MANY_CLAIM_ITEMS".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "理赔明细项目数量偏多".into(),
            },
        },
        Rule {
            rule_id: "rule_peer_p95_amount".into(),
            version: 1,
            name: "Peer P95 amount".into(),
            review_mode: "both".into(),
            scheme_family: Some("provider_peer_outlier".into()),
            conditions: vec![Condition {
                field: "claim_amount_peer_percentile".into(),
                operator: ">=".into(),
                value: serde_json::json!(95),
            }],
            action: RuleAction {
                score: 25,
                alert_code: "PEER_P95_AMOUNT".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "理赔金额高于同类样本 P95".into(),
            },
        },
        Rule {
            rule_id: "rule_peer_p99_amount".into(),
            version: 1,
            name: "Peer P99 amount".into(),
            review_mode: "both".into(),
            scheme_family: Some("provider_peer_outlier".into()),
            conditions: vec![Condition {
                field: "claim_amount_peer_percentile".into(),
                operator: ">=".into(),
                value: serde_json::json!(99),
            }],
            action: RuleAction {
                score: 40,
                alert_code: "PEER_P99_AMOUNT".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "理赔金额高于同类样本 P99".into(),
            },
        },
        Rule {
            rule_id: "rule_provider_high_risk_tier".into(),
            version: 1,
            name: "Provider high risk tier".into(),
            review_mode: "both".into(),
            scheme_family: Some("provider_peer_outlier".into()),
            conditions: vec![Condition {
                field: "provider_risk_tier".into(),
                operator: "==".into(),
                value: serde_json::json!("HIGH"),
            }],
            action: RuleAction {
                score: 30,
                alert_code: "PROVIDER_HIGH_RISK_TIER".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "Provider 风险等级较高".into(),
            },
        },
        Rule {
            rule_id: "rule_provider_profile_high".into(),
            version: 1,
            name: "Provider profile high".into(),
            review_mode: "both".into(),
            scheme_family: Some("provider_peer_outlier".into()),
            conditions: vec![Condition {
                field: "provider_profile_score".into(),
                operator: ">=".into(),
                value: serde_json::json!(70),
            }],
            action: RuleAction {
                score: 30,
                alert_code: "PROVIDER_PROFILE_HIGH".into(),
                recommended_action: RecommendedAction::ManualReview,
                action_class: RuleActionClass::ManualReview,
                required_evidence: vec![],
                adjudication_policy: None,
                reason: "Provider 风险画像分偏高".into(),
            },
        },
    ]
}

pub(super) fn default_rule_details() -> Vec<RuleDetailRecord> {
    default_runtime_rules()
        .into_iter()
        .map(|rule| rule_detail_from_rule(rule, "active", "rules-ops".into()))
        .collect()
}
